import Document, {
  DocumentContext,
  Html,
  Head,
  Main,
  NextScript,
} from 'next/document';
import { ServerStyleSheet } from 'styled-components';

export default class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: [initialProps.styles, sheet.getStyleElement()],
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="mask-icon"
            href="https://github.githubassets.com/pinned-octocat.svg"
            color="#000000"
          />
          <link
            rel="alternate icon"
            className="js-site-favicon"
            type="image/png"
            href="https://github.githubassets.com/favicons/favicon-dark.png"
          />
          <link
            rel="icon"
            className="js-site-favicon"
            type="image/svg+xml"
            href="https://github.githubassets.com/favicons/favicon-dark.svg"
          />
          <link
            href="http://fonts.cdnfonts.com/css/segoe-ui-4"
            rel="stylesheet"
          />
          <link
            href="http://fonts.cdnfonts.com/css/helvetica-255"
            rel="stylesheet"
          />
          <link href="http://fonts.cdnfonts.com/css/arial" rel="stylesheet" />
          <link href="http://fonts.cdnfonts.com/css/menlo" rel="stylesheet" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
